all: mypipeline

mypipeline: mypipeline.o
	gcc -m32 -g -Wall -o mypipeline mypipeline.o
	rm *.o

mypipeline.o: mypipeline.c
	gcc -m32 -g -Wall -c -o mypipeline.o mypipeline.c
	
.PHONY: clean
clean:
	rm -f mypipeline